# -*- coding: utf-8 -*-
"""week3 assignment

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FXV4k5lhmucvgeuxmOkLzjFHN5fLqZHS
"""

scores =(60,40,10,30,50)
print (scores)

total = 0
for score in scores:
  total = total + score
print (total)
average = total / len(scores)
print (average)

highest = scores[0]
for score in scores:
  if score > highest:
    highest = score
print (highest)

student1 = {'name': 'caleb','math': 66,'chemistry':77}
student2 = {'name': 'demian','math': 79,'chemistry':39}
student3 = {'name': 'manasseh', 'math': 88, 'chemistry':99}
student4 = {'name': 'paul', 'math': 53, 'chemistry':79}
student5 = {'name': 'judge', 'math':64, 'chemistry':89}
student = [student1,student2,student3,student4,student5]
print (student1)
print (student2)
print (student3)
print (student4)
print (student5)
print (student)

#if a =88 and is the highest maths score and 80 is the highest chemistry score lets use a in terms of maths and b in terms of chemistry

student3 = 88,'math'
student5 = 80,'chemistry'
print (student3)
print (student5)

subjets =  ('Biology','physics','maths','geography','english')
print (subject)

score = (55.7,99.6,34,43.7,99.9)
print(score)

"""The above codes is for the week 3 assignment
course DTS
the following below is the assignment question
1. create a list of 5 student
2. compute the average score
3. find the highest score
4. creat a dictionary with 5 students and score
5. find the highest scoring student
6. creat a tuple of subjects
7. create a set of unique scores
the following attempts are above in the following code
> click the above right side of each of the codes to run the answer
BY: ANYUGU CALEB AONDONGU.
DEPARTMENT: DATA SCENCE

"""